name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/
          key: ${{ runner.OS }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.OS }}-maven-${{ hashFiles('pom.xml') }}-
            ${{ runner.OS }}-maven-
            ${{ runner.OS }}-

      - name: Build
        run: mvn package --file pom.xml -Pfast
      - name: Tests
        run: mvn install
      # https://app.codecov.io/gh/solven-eu/cleanthat/new
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Spotless Check
        run: mvn spotless:check || mvn spotless:apply && git commit -m "mvn spotless:apply" && git push